package com.pgy.ups.biz.business.dao.mapper.renewalDetail;


import com.pgy.ups.biz.facade.model.borrowCash.LsdBorrowCash;
import com.pgy.ups.biz.facade.model.renewalDetail.LsdRenewalDetail;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface LsdRenewalDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_renewal_detail
     *
     * @mbggenerated Fri Oct 19 16:23:46 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_renewal_detail
     *
     * @mbggenerated Fri Oct 19 16:23:46 CST 2018
     */
    int insert(LsdRenewalDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_renewal_detail
     *
     * @mbggenerated Fri Oct 19 16:23:46 CST 2018
     */
    int insertSelective(LsdRenewalDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_renewal_detail
     *
     * @mbggenerated Fri Oct 19 16:23:46 CST 2018
     */
    LsdRenewalDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_renewal_detail
     *
     * @mbggenerated Fri Oct 19 16:23:46 CST 2018
     */
    int updateByPrimaryKeySelective(LsdRenewalDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_renewal_detail
     *
     * @mbggenerated Fri Oct 19 16:23:46 CST 2018
     */
    int updateByPrimaryKey(LsdRenewalDetail record);

    List<LsdRenewalDetail> getEverydayList(@Param("startDate") Date startDate, @Param("endDate") Date endDate);
}