package com.pgy.ups.biz.facade.model.borrowCash;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LsdBorrowCash implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.is_delete
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Long isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.gmt_create
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.gmt_modified
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.gmt_repay
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Date gmtRepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.borrow_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String borrowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.borrow_type
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte borrowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.user_id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.borrow_days
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte borrowDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.review_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte reviewStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.rish_order_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String rishOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.arrival_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal arrivalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.activity_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal activityAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.gmt_arrival
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Date gmtArrival;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.ups_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String upsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.gmt_plan_repayment
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Date gmtPlanRepayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.poundage
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal poundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.rate_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal rateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.repay_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal repayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.card_number
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.card_name
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.gmt_close
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Date gmtClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.close_reason
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String closeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.overdue_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte overdueStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.current_overdue_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte currentOverdueStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.overdue_day
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Long overdueDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.overdue_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal overdueAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.sum_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal sumRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.sum_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal sumOverdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.sum_rebate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal sumRebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.sum_renewal_poundage
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal sumRenewalPoundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.credit_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal creditOverdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.renewal_num
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Long renewalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.latitude
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.longitude
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.province
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.city
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.county
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.address
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.success_num
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.poundage_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal poundageRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.base_bank_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal baseBankRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.borrow_use
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Byte borrowUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.consume_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal consumeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.overdue_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal overdueRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.real_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal realOverdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.user_coupon_id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private Long userCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.coupon_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal couponAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.current_quota
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private BigDecimal currentQuota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_borrow_cash.remark
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private String remark;


    private String tradeNo;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lsd_borrow_cash
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.id
     *
     * @return the value of lsd_borrow_cash.id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.id
     *
     * @param id the value for lsd_borrow_cash.id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.is_delete
     *
     * @return the value of lsd_borrow_cash.is_delete
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Long getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.is_delete
     *
     * @param isDelete the value for lsd_borrow_cash.is_delete
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setIsDelete(Long isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.gmt_create
     *
     * @return the value of lsd_borrow_cash.gmt_create
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.gmt_create
     *
     * @param gmtCreate the value for lsd_borrow_cash.gmt_create
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.gmt_modified
     *
     * @return the value of lsd_borrow_cash.gmt_modified
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.gmt_modified
     *
     * @param gmtModified the value for lsd_borrow_cash.gmt_modified
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.gmt_repay
     *
     * @return the value of lsd_borrow_cash.gmt_repay
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Date getGmtRepay() {
        return gmtRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.gmt_repay
     *
     * @param gmtRepay the value for lsd_borrow_cash.gmt_repay
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setGmtRepay(Date gmtRepay) {
        this.gmtRepay = gmtRepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.borrow_no
     *
     * @return the value of lsd_borrow_cash.borrow_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getBorrowNo() {
        return borrowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.borrow_no
     *
     * @param borrowNo the value for lsd_borrow_cash.borrow_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setBorrowNo(String borrowNo) {
        this.borrowNo = borrowNo == null ? null : borrowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.borrow_type
     *
     * @return the value of lsd_borrow_cash.borrow_type
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getBorrowType() {
        return borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.borrow_type
     *
     * @param borrowType the value for lsd_borrow_cash.borrow_type
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setBorrowType(Byte borrowType) {
        this.borrowType = borrowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.user_id
     *
     * @return the value of lsd_borrow_cash.user_id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.user_id
     *
     * @param userId the value for lsd_borrow_cash.user_id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.borrow_days
     *
     * @return the value of lsd_borrow_cash.borrow_days
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getBorrowDays() {
        return borrowDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.borrow_days
     *
     * @param borrowDays the value for lsd_borrow_cash.borrow_days
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setBorrowDays(Byte borrowDays) {
        this.borrowDays = borrowDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.amount
     *
     * @return the value of lsd_borrow_cash.amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.amount
     *
     * @param amount the value for lsd_borrow_cash.amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.status
     *
     * @return the value of lsd_borrow_cash.status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.status
     *
     * @param status the value for lsd_borrow_cash.status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.review_status
     *
     * @return the value of lsd_borrow_cash.review_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getReviewStatus() {
        return reviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.review_status
     *
     * @param reviewStatus the value for lsd_borrow_cash.review_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setReviewStatus(Byte reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.rish_order_no
     *
     * @return the value of lsd_borrow_cash.rish_order_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getRishOrderNo() {
        return rishOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.rish_order_no
     *
     * @param rishOrderNo the value for lsd_borrow_cash.rish_order_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setRishOrderNo(String rishOrderNo) {
        this.rishOrderNo = rishOrderNo == null ? null : rishOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.arrival_amount
     *
     * @return the value of lsd_borrow_cash.arrival_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getArrivalAmount() {
        return arrivalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.arrival_amount
     *
     * @param arrivalAmount the value for lsd_borrow_cash.arrival_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setArrivalAmount(BigDecimal arrivalAmount) {
        this.arrivalAmount = arrivalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.activity_amount
     *
     * @return the value of lsd_borrow_cash.activity_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getActivityAmount() {
        return activityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.activity_amount
     *
     * @param activityAmount the value for lsd_borrow_cash.activity_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setActivityAmount(BigDecimal activityAmount) {
        this.activityAmount = activityAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.gmt_arrival
     *
     * @return the value of lsd_borrow_cash.gmt_arrival
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Date getGmtArrival() {
        return gmtArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.gmt_arrival
     *
     * @param gmtArrival the value for lsd_borrow_cash.gmt_arrival
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setGmtArrival(Date gmtArrival) {
        this.gmtArrival = gmtArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.ups_no
     *
     * @return the value of lsd_borrow_cash.ups_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getUpsNo() {
        return upsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.ups_no
     *
     * @param upsNo the value for lsd_borrow_cash.ups_no
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setUpsNo(String upsNo) {
        this.upsNo = upsNo == null ? null : upsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.gmt_plan_repayment
     *
     * @return the value of lsd_borrow_cash.gmt_plan_repayment
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Date getGmtPlanRepayment() {
        return gmtPlanRepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.gmt_plan_repayment
     *
     * @param gmtPlanRepayment the value for lsd_borrow_cash.gmt_plan_repayment
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setGmtPlanRepayment(Date gmtPlanRepayment) {
        this.gmtPlanRepayment = gmtPlanRepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.poundage
     *
     * @return the value of lsd_borrow_cash.poundage
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getPoundage() {
        return poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.poundage
     *
     * @param poundage the value for lsd_borrow_cash.poundage
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setPoundage(BigDecimal poundage) {
        this.poundage = poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.rate_amount
     *
     * @return the value of lsd_borrow_cash.rate_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getRateAmount() {
        return rateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.rate_amount
     *
     * @param rateAmount the value for lsd_borrow_cash.rate_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setRateAmount(BigDecimal rateAmount) {
        this.rateAmount = rateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.repay_amount
     *
     * @return the value of lsd_borrow_cash.repay_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getRepayAmount() {
        return repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.repay_amount
     *
     * @param repayAmount the value for lsd_borrow_cash.repay_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setRepayAmount(BigDecimal repayAmount) {
        this.repayAmount = repayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.card_number
     *
     * @return the value of lsd_borrow_cash.card_number
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.card_number
     *
     * @param cardNumber the value for lsd_borrow_cash.card_number
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.card_name
     *
     * @return the value of lsd_borrow_cash.card_name
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.card_name
     *
     * @param cardName the value for lsd_borrow_cash.card_name
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.gmt_close
     *
     * @return the value of lsd_borrow_cash.gmt_close
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Date getGmtClose() {
        return gmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.gmt_close
     *
     * @param gmtClose the value for lsd_borrow_cash.gmt_close
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setGmtClose(Date gmtClose) {
        this.gmtClose = gmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.close_reason
     *
     * @return the value of lsd_borrow_cash.close_reason
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getCloseReason() {
        return closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.close_reason
     *
     * @param closeReason the value for lsd_borrow_cash.close_reason
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCloseReason(String closeReason) {
        this.closeReason = closeReason == null ? null : closeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.overdue_status
     *
     * @return the value of lsd_borrow_cash.overdue_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getOverdueStatus() {
        return overdueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.overdue_status
     *
     * @param overdueStatus the value for lsd_borrow_cash.overdue_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setOverdueStatus(Byte overdueStatus) {
        this.overdueStatus = overdueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.current_overdue_status
     *
     * @return the value of lsd_borrow_cash.current_overdue_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getCurrentOverdueStatus() {
        return currentOverdueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.current_overdue_status
     *
     * @param currentOverdueStatus the value for lsd_borrow_cash.current_overdue_status
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCurrentOverdueStatus(Byte currentOverdueStatus) {
        this.currentOverdueStatus = currentOverdueStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.overdue_day
     *
     * @return the value of lsd_borrow_cash.overdue_day
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Long getOverdueDay() {
        return overdueDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.overdue_day
     *
     * @param overdueDay the value for lsd_borrow_cash.overdue_day
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setOverdueDay(Long overdueDay) {
        this.overdueDay = overdueDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.overdue_amount
     *
     * @return the value of lsd_borrow_cash.overdue_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getOverdueAmount() {
        return overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.overdue_amount
     *
     * @param overdueAmount the value for lsd_borrow_cash.overdue_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setOverdueAmount(BigDecimal overdueAmount) {
        this.overdueAmount = overdueAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.sum_rate
     *
     * @return the value of lsd_borrow_cash.sum_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getSumRate() {
        return sumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.sum_rate
     *
     * @param sumRate the value for lsd_borrow_cash.sum_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setSumRate(BigDecimal sumRate) {
        this.sumRate = sumRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.sum_overdue
     *
     * @return the value of lsd_borrow_cash.sum_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getSumOverdue() {
        return sumOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.sum_overdue
     *
     * @param sumOverdue the value for lsd_borrow_cash.sum_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setSumOverdue(BigDecimal sumOverdue) {
        this.sumOverdue = sumOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.sum_rebate
     *
     * @return the value of lsd_borrow_cash.sum_rebate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getSumRebate() {
        return sumRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.sum_rebate
     *
     * @param sumRebate the value for lsd_borrow_cash.sum_rebate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setSumRebate(BigDecimal sumRebate) {
        this.sumRebate = sumRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.sum_renewal_poundage
     *
     * @return the value of lsd_borrow_cash.sum_renewal_poundage
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getSumRenewalPoundage() {
        return sumRenewalPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.sum_renewal_poundage
     *
     * @param sumRenewalPoundage the value for lsd_borrow_cash.sum_renewal_poundage
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setSumRenewalPoundage(BigDecimal sumRenewalPoundage) {
        this.sumRenewalPoundage = sumRenewalPoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.credit_overdue
     *
     * @return the value of lsd_borrow_cash.credit_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getCreditOverdue() {
        return creditOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.credit_overdue
     *
     * @param creditOverdue the value for lsd_borrow_cash.credit_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCreditOverdue(BigDecimal creditOverdue) {
        this.creditOverdue = creditOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.renewal_num
     *
     * @return the value of lsd_borrow_cash.renewal_num
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Long getRenewalNum() {
        return renewalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.renewal_num
     *
     * @param renewalNum the value for lsd_borrow_cash.renewal_num
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setRenewalNum(Long renewalNum) {
        this.renewalNum = renewalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.latitude
     *
     * @return the value of lsd_borrow_cash.latitude
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.latitude
     *
     * @param latitude the value for lsd_borrow_cash.latitude
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.longitude
     *
     * @return the value of lsd_borrow_cash.longitude
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.longitude
     *
     * @param longitude the value for lsd_borrow_cash.longitude
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.province
     *
     * @return the value of lsd_borrow_cash.province
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.province
     *
     * @param province the value for lsd_borrow_cash.province
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.city
     *
     * @return the value of lsd_borrow_cash.city
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.city
     *
     * @param city the value for lsd_borrow_cash.city
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.county
     *
     * @return the value of lsd_borrow_cash.county
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.county
     *
     * @param county the value for lsd_borrow_cash.county
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.address
     *
     * @return the value of lsd_borrow_cash.address
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.address
     *
     * @param address the value for lsd_borrow_cash.address
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.success_num
     *
     * @return the value of lsd_borrow_cash.success_num
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.success_num
     *
     * @param successNum the value for lsd_borrow_cash.success_num
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setSuccessNum(Byte successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.poundage_rate
     *
     * @return the value of lsd_borrow_cash.poundage_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getPoundageRate() {
        return poundageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.poundage_rate
     *
     * @param poundageRate the value for lsd_borrow_cash.poundage_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setPoundageRate(BigDecimal poundageRate) {
        this.poundageRate = poundageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.base_bank_rate
     *
     * @return the value of lsd_borrow_cash.base_bank_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getBaseBankRate() {
        return baseBankRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.base_bank_rate
     *
     * @param baseBankRate the value for lsd_borrow_cash.base_bank_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setBaseBankRate(BigDecimal baseBankRate) {
        this.baseBankRate = baseBankRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.borrow_use
     *
     * @return the value of lsd_borrow_cash.borrow_use
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Byte getBorrowUse() {
        return borrowUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.borrow_use
     *
     * @param borrowUse the value for lsd_borrow_cash.borrow_use
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setBorrowUse(Byte borrowUse) {
        this.borrowUse = borrowUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.consume_amount
     *
     * @return the value of lsd_borrow_cash.consume_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getConsumeAmount() {
        return consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.consume_amount
     *
     * @param consumeAmount the value for lsd_borrow_cash.consume_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setConsumeAmount(BigDecimal consumeAmount) {
        this.consumeAmount = consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.overdue_rate
     *
     * @return the value of lsd_borrow_cash.overdue_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getOverdueRate() {
        return overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.overdue_rate
     *
     * @param overdueRate the value for lsd_borrow_cash.overdue_rate
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setOverdueRate(BigDecimal overdueRate) {
        this.overdueRate = overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.real_overdue
     *
     * @return the value of lsd_borrow_cash.real_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getRealOverdue() {
        return realOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.real_overdue
     *
     * @param realOverdue the value for lsd_borrow_cash.real_overdue
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setRealOverdue(BigDecimal realOverdue) {
        this.realOverdue = realOverdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.user_coupon_id
     *
     * @return the value of lsd_borrow_cash.user_coupon_id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public Long getUserCouponId() {
        return userCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.user_coupon_id
     *
     * @param userCouponId the value for lsd_borrow_cash.user_coupon_id
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setUserCouponId(Long userCouponId) {
        this.userCouponId = userCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.coupon_amount
     *
     * @return the value of lsd_borrow_cash.coupon_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.coupon_amount
     *
     * @param couponAmount the value for lsd_borrow_cash.coupon_amount
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.current_quota
     *
     * @return the value of lsd_borrow_cash.current_quota
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public BigDecimal getCurrentQuota() {
        return currentQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.current_quota
     *
     * @param currentQuota the value for lsd_borrow_cash.current_quota
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setCurrentQuota(BigDecimal currentQuota) {
        this.currentQuota = currentQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_borrow_cash.remark
     *
     * @return the value of lsd_borrow_cash.remark
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_borrow_cash.remark
     *
     * @param remark the value for lsd_borrow_cash.remark
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_borrow_cash
     *
     * @mbggenerated Mon Oct 22 11:40:57 CST 2018
     */

    public String getTradeNo() {
        return tradeNo;
    }

    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", gmtRepay=").append(gmtRepay);
        sb.append(", borrowNo=").append(borrowNo);
        sb.append(", borrowType=").append(borrowType);
        sb.append(", userId=").append(userId);
        sb.append(", borrowDays=").append(borrowDays);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", reviewStatus=").append(reviewStatus);
        sb.append(", rishOrderNo=").append(rishOrderNo);
        sb.append(", arrivalAmount=").append(arrivalAmount);
        sb.append(", activityAmount=").append(activityAmount);
        sb.append(", gmtArrival=").append(gmtArrival);
        sb.append(", upsNo=").append(upsNo);
        sb.append(", gmtPlanRepayment=").append(gmtPlanRepayment);
        sb.append(", poundage=").append(poundage);
        sb.append(", rateAmount=").append(rateAmount);
        sb.append(", repayAmount=").append(repayAmount);
        sb.append(", cardNumber=").append(cardNumber);
        sb.append(", cardName=").append(cardName);
        sb.append(", gmtClose=").append(gmtClose);
        sb.append(", closeReason=").append(closeReason);
        sb.append(", overdueStatus=").append(overdueStatus);
        sb.append(", currentOverdueStatus=").append(currentOverdueStatus);
        sb.append(", overdueDay=").append(overdueDay);
        sb.append(", overdueAmount=").append(overdueAmount);
        sb.append(", sumRate=").append(sumRate);
        sb.append(", sumOverdue=").append(sumOverdue);
        sb.append(", sumRebate=").append(sumRebate);
        sb.append(", sumRenewalPoundage=").append(sumRenewalPoundage);
        sb.append(", creditOverdue=").append(creditOverdue);
        sb.append(", renewalNum=").append(renewalNum);
        sb.append(", latitude=").append(latitude);
        sb.append(", longitude=").append(longitude);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", county=").append(county);
        sb.append(", address=").append(address);
        sb.append(", successNum=").append(successNum);
        sb.append(", poundageRate=").append(poundageRate);
        sb.append(", baseBankRate=").append(baseBankRate);
        sb.append(", borrowUse=").append(borrowUse);
        sb.append(", consumeAmount=").append(consumeAmount);
        sb.append(", overdueRate=").append(overdueRate);
        sb.append(", realOverdue=").append(realOverdue);
        sb.append(", userCouponId=").append(userCouponId);
        sb.append(", couponAmount=").append(couponAmount);
        sb.append(", currentQuota=").append(currentQuota);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}