package com.pgy.ups.biz.facade.model.repaymentBorrowCash;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LsdRepaymentBorrowCash implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.is_delete
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.gmt_create
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.gmt_modified
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.repay_type
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Byte repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.repay_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String repayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.user_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.status
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.repayment_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private BigDecimal repaymentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.actual_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private BigDecimal actualAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.borrow_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Long borrowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.pay_trade_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String payTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.trade_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.user_coupon_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private Long userCouponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.coupon_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private BigDecimal couponAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.rebate_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private BigDecimal rebateAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.card_number
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.card_name
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.fail_reason
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lsd_repayment_borrow_cash.remark
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lsd_repayment_borrow_cash
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.id
     *
     * @return the value of lsd_repayment_borrow_cash.id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.id
     *
     * @param id the value for lsd_repayment_borrow_cash.id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.is_delete
     *
     * @return the value of lsd_repayment_borrow_cash.is_delete
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.is_delete
     *
     * @param isDelete the value for lsd_repayment_borrow_cash.is_delete
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.gmt_create
     *
     * @return the value of lsd_repayment_borrow_cash.gmt_create
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.gmt_create
     *
     * @param gmtCreate the value for lsd_repayment_borrow_cash.gmt_create
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.gmt_modified
     *
     * @return the value of lsd_repayment_borrow_cash.gmt_modified
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.gmt_modified
     *
     * @param gmtModified the value for lsd_repayment_borrow_cash.gmt_modified
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.repay_type
     *
     * @return the value of lsd_repayment_borrow_cash.repay_type
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Byte getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.repay_type
     *
     * @param repayType the value for lsd_repayment_borrow_cash.repay_type
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setRepayType(Byte repayType) {
        this.repayType = repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.repay_no
     *
     * @return the value of lsd_repayment_borrow_cash.repay_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getRepayNo() {
        return repayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.repay_no
     *
     * @param repayNo the value for lsd_repayment_borrow_cash.repay_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setRepayNo(String repayNo) {
        this.repayNo = repayNo == null ? null : repayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.user_id
     *
     * @return the value of lsd_repayment_borrow_cash.user_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.user_id
     *
     * @param userId the value for lsd_repayment_borrow_cash.user_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.status
     *
     * @return the value of lsd_repayment_borrow_cash.status
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.status
     *
     * @param status the value for lsd_repayment_borrow_cash.status
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.repayment_amount
     *
     * @return the value of lsd_repayment_borrow_cash.repayment_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public BigDecimal getRepaymentAmount() {
        return repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.repayment_amount
     *
     * @param repaymentAmount the value for lsd_repayment_borrow_cash.repayment_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setRepaymentAmount(BigDecimal repaymentAmount) {
        this.repaymentAmount = repaymentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.actual_amount
     *
     * @return the value of lsd_repayment_borrow_cash.actual_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.actual_amount
     *
     * @param actualAmount the value for lsd_repayment_borrow_cash.actual_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.borrow_id
     *
     * @return the value of lsd_repayment_borrow_cash.borrow_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Long getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.borrow_id
     *
     * @param borrowId the value for lsd_repayment_borrow_cash.borrow_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setBorrowId(Long borrowId) {
        this.borrowId = borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.pay_trade_no
     *
     * @return the value of lsd_repayment_borrow_cash.pay_trade_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getPayTradeNo() {
        return payTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.pay_trade_no
     *
     * @param payTradeNo the value for lsd_repayment_borrow_cash.pay_trade_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setPayTradeNo(String payTradeNo) {
        this.payTradeNo = payTradeNo == null ? null : payTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.trade_no
     *
     * @return the value of lsd_repayment_borrow_cash.trade_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.trade_no
     *
     * @param tradeNo the value for lsd_repayment_borrow_cash.trade_no
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.user_coupon_id
     *
     * @return the value of lsd_repayment_borrow_cash.user_coupon_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public Long getUserCouponId() {
        return userCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.user_coupon_id
     *
     * @param userCouponId the value for lsd_repayment_borrow_cash.user_coupon_id
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setUserCouponId(Long userCouponId) {
        this.userCouponId = userCouponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.coupon_amount
     *
     * @return the value of lsd_repayment_borrow_cash.coupon_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public BigDecimal getCouponAmount() {
        return couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.coupon_amount
     *
     * @param couponAmount the value for lsd_repayment_borrow_cash.coupon_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setCouponAmount(BigDecimal couponAmount) {
        this.couponAmount = couponAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.rebate_amount
     *
     * @return the value of lsd_repayment_borrow_cash.rebate_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public BigDecimal getRebateAmount() {
        return rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.rebate_amount
     *
     * @param rebateAmount the value for lsd_repayment_borrow_cash.rebate_amount
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setRebateAmount(BigDecimal rebateAmount) {
        this.rebateAmount = rebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.card_number
     *
     * @return the value of lsd_repayment_borrow_cash.card_number
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.card_number
     *
     * @param cardNumber the value for lsd_repayment_borrow_cash.card_number
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.card_name
     *
     * @return the value of lsd_repayment_borrow_cash.card_name
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.card_name
     *
     * @param cardName the value for lsd_repayment_borrow_cash.card_name
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.fail_reason
     *
     * @return the value of lsd_repayment_borrow_cash.fail_reason
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.fail_reason
     *
     * @param failReason the value for lsd_repayment_borrow_cash.fail_reason
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lsd_repayment_borrow_cash.remark
     *
     * @return the value of lsd_repayment_borrow_cash.remark
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lsd_repayment_borrow_cash.remark
     *
     * @param remark the value for lsd_repayment_borrow_cash.remark
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lsd_repayment_borrow_cash
     *
     * @mbggenerated Fri Oct 19 14:29:51 CST 2018
     */

    private  String borrowNo;

    public String getBorrowNo() {
        return borrowNo;
    }

    public void setBorrowNo(String borrowNo) {
        this.borrowNo = borrowNo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", repayType=").append(repayType);
        sb.append(", repayNo=").append(repayNo);
        sb.append(", userId=").append(userId);
        sb.append(", status=").append(status);
        sb.append(", repaymentAmount=").append(repaymentAmount);
        sb.append(", actualAmount=").append(actualAmount);
        sb.append(", borrowId=").append(borrowId);
        sb.append(", payTradeNo=").append(payTradeNo);
        sb.append(", tradeNo=").append(tradeNo);
        sb.append(", userCouponId=").append(userCouponId);
        sb.append(", couponAmount=").append(couponAmount);
        sb.append(", rebateAmount=").append(rebateAmount);
        sb.append(", cardNumber=").append(cardNumber);
        sb.append(", cardName=").append(cardName);
        sb.append(", failReason=").append(failReason);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}