package com.pgy.ups.biz.business.dao.mapper.sysCronJob;

import com.pgy.ups.biz.facade.model.sysCronJob.SysCronJob;

public interface SysCronJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    int insert(SysCronJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    int insertSelective(SysCronJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    SysCronJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    int updateByPrimaryKeySelective(SysCronJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    int updateByPrimaryKey(SysCronJob record);
}