package com.pgy.ups.biz.facade.model.sysCronJob;

import java.io.Serializable;
import java.util.Date;

public class SysCronJob implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.id
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.is_delete
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.gmt_create
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.gmt_modified
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.creator
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.modifier
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.name
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.bean_id
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String beanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.cron
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String cron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.ip
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.is_open
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Byte isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.last_excute_time
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Date lastExcuteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.intro
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_cron_job.job_type
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private Byte jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.id
     *
     * @return the value of sys_cron_job.id
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.id
     *
     * @param id the value for sys_cron_job.id
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.is_delete
     *
     * @return the value of sys_cron_job.is_delete
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.is_delete
     *
     * @param isDelete the value for sys_cron_job.is_delete
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.gmt_create
     *
     * @return the value of sys_cron_job.gmt_create
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.gmt_create
     *
     * @param gmtCreate the value for sys_cron_job.gmt_create
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.gmt_modified
     *
     * @return the value of sys_cron_job.gmt_modified
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.gmt_modified
     *
     * @param gmtModified the value for sys_cron_job.gmt_modified
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.creator
     *
     * @return the value of sys_cron_job.creator
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.creator
     *
     * @param creator the value for sys_cron_job.creator
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.modifier
     *
     * @return the value of sys_cron_job.modifier
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.modifier
     *
     * @param modifier the value for sys_cron_job.modifier
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.name
     *
     * @return the value of sys_cron_job.name
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.name
     *
     * @param name the value for sys_cron_job.name
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.bean_id
     *
     * @return the value of sys_cron_job.bean_id
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getBeanId() {
        return beanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.bean_id
     *
     * @param beanId the value for sys_cron_job.bean_id
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setBeanId(String beanId) {
        this.beanId = beanId == null ? null : beanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.cron
     *
     * @return the value of sys_cron_job.cron
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.cron
     *
     * @param cron the value for sys_cron_job.cron
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.ip
     *
     * @return the value of sys_cron_job.ip
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.ip
     *
     * @param ip the value for sys_cron_job.ip
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.is_open
     *
     * @return the value of sys_cron_job.is_open
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Byte getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.is_open
     *
     * @param isOpen the value for sys_cron_job.is_open
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setIsOpen(Byte isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.last_excute_time
     *
     * @return the value of sys_cron_job.last_excute_time
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Date getLastExcuteTime() {
        return lastExcuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.last_excute_time
     *
     * @param lastExcuteTime the value for sys_cron_job.last_excute_time
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setLastExcuteTime(Date lastExcuteTime) {
        this.lastExcuteTime = lastExcuteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.intro
     *
     * @return the value of sys_cron_job.intro
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.intro
     *
     * @param intro the value for sys_cron_job.intro
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_cron_job.job_type
     *
     * @return the value of sys_cron_job.job_type
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public Byte getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_cron_job.job_type
     *
     * @param jobType the value for sys_cron_job.job_type
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    public void setJobType(Byte jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cron_job
     *
     * @mbggenerated Wed Oct 24 20:41:23 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", creator=").append(creator);
        sb.append(", modifier=").append(modifier);
        sb.append(", name=").append(name);
        sb.append(", beanId=").append(beanId);
        sb.append(", cron=").append(cron);
        sb.append(", ip=").append(ip);
        sb.append(", isOpen=").append(isOpen);
        sb.append(", lastExcuteTime=").append(lastExcuteTime);
        sb.append(", intro=").append(intro);
        sb.append(", jobType=").append(jobType);
        sb.append("]");
        return sb.toString();
    }
}