package com.pgy.ups.biz.facade.model.upsCheckAccounts;

import java.io.Serializable;
import java.util.Date;

public class UpsCheckAccounts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.id
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.is_delete
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.gmt_create
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.gmt_modified
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.proofread_type
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private String proofreadType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.return_code
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private  Boolean  returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.ymd
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private String ymd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.creator
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.modifier
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ups_check accounts.from_system
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private String fromSystem;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.id
     *
     * @return the value of ups_check accounts.id
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.id
     *
     * @param id the value for ups_check accounts.id
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.is_delete
     *
     * @return the value of ups_check accounts.is_delete
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.is_delete
     *
     * @param isDelete the value for ups_check accounts.is_delete
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.gmt_create
     *
     * @return the value of ups_check accounts.gmt_create
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.gmt_create
     *
     * @param gmtCreate the value for ups_check accounts.gmt_create
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.gmt_modified
     *
     * @return the value of ups_check accounts.gmt_modified
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.gmt_modified
     *
     * @param gmtModified the value for ups_check accounts.gmt_modified
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.proofread_type
     *
     * @return the value of ups_check accounts.proofread_type
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public String getProofreadType() {
        return proofreadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.proofread_type
     *
     * @param proofreadType the value for ups_check accounts.proofread_type
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setProofreadType(String proofreadType) {
        this.proofreadType = proofreadType == null ? null : proofreadType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.return_code
     *
     * @return the value of ups_check accounts.return_code
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.return_code
     *
     * @param returnCode the value for ups_check accounts.return_code
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.ymd
     *
     * @return the value of ups_check accounts.ymd
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public String getYmd() {
        return ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.ymd
     *
     * @param ymd the value for ups_check accounts.ymd
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setYmd(String ymd) {
        this.ymd = ymd == null ? null : ymd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.creator
     *
     * @return the value of ups_check accounts.creator
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.creator
     *
     * @param creator the value for ups_check accounts.creator
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.modifier
     *
     * @return the value of ups_check accounts.modifier
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.modifier
     *
     * @param modifier the value for ups_check accounts.modifier
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ups_check accounts.from_system
     *
     * @return the value of ups_check accounts.from_system
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public String getFromSystem() {
        return fromSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ups_check accounts.from_system
     *
     * @param fromSystem the value for ups_check accounts.from_system
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    public void setFromSystem(String fromSystem) {
        this.fromSystem = fromSystem == null ? null : fromSystem.trim();
    }

    public Boolean getReturnCode() {
        return returnCode;
    }

    public void setReturnCode(Boolean returnCode) {
        this.returnCode = returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", proofreadType=").append(proofreadType);
        sb.append(", returnCode=").append(returnCode);
        sb.append(", ymd=").append(ymd);
        sb.append(", creator=").append(creator);
        sb.append(", modifier=").append(modifier);
        sb.append(", fromSystem=").append(fromSystem);
        sb.append("]");
        return sb.toString();
    }
}