package com.pgy.ups.account.business.dao.mapper;


import com.pay.ups.account.facade.from.Form;
import com.pgy.ups.account.business.dao.domain.AuthSignConfig;


import java.util.List;

public interface AuthSignConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sign_config
     *
     * @mbggenerated Wed Oct 10 19:48:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sign_config
     *
     * @mbggenerated Wed Oct 10 19:48:27 CST 2018
     */
    int insert(AuthSignConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sign_config
     *
     * @mbggenerated Wed Oct 10 19:48:27 CST 2018
     */
    int insertSelective(AuthSignConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sign_config
     *
     * @mbggenerated Wed Oct 10 19:48:27 CST 2018
     */
    AuthSignConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sign_config
     *
     * @mbggenerated Wed Oct 10 19:48:27 CST 2018
     */
    int updateByPrimaryKeySelective(AuthSignConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sign_config
     *
     * @mbggenerated Wed Oct 10 19:48:27 CST 2018
     */
    int updateByPrimaryKey(AuthSignConfig record);

     List<AuthSignConfig> selectPage(Form base);
}