package com.pgy.ups.biz.business.dao.mapper.upsCheckAccounts;

import com.pgy.ups.biz.facade.model.upsCheckAccounts.UpsCheckAccounts;
import org.apache.ibatis.annotations.Param;

public interface UpsCheckAccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    int insert(UpsCheckAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    int insertSelective(UpsCheckAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    UpsCheckAccounts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    int updateByPrimaryKeySelective(UpsCheckAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ups_check accounts
     *
     * @mbggenerated Tue Oct 23 20:35:19 CST 2018
     */
    int updateByPrimaryKey(UpsCheckAccounts record);

    UpsCheckAccounts getRecordTypeAndYmd(@Param("proofreadType") String proofreadType,@Param("ymd")  String ymd,@Param("returnCode") Boolean  flag);
}